meta_product_name: "Goat's Guide"
meta_title: "Goat's Guide"
meta_description: "More metal"
meta_image: "" # should exist in `app/assets/images/`
twitter_account: "@goatsguide"   # required for Twitter Cards
