meta_product_name: "Goat's Guide"
meta_title: "Goat's Guide | More metal shows please."
meta_description: "The summit for all you extreme sound enthusiasts. Discover more metal events. Post upcoming shows you know about on a site devoted to the left-hand path. Death Metal - Black Metal - Crust - Tech - Doom - Whatever. Just make sure it's fucking disgusting."
meta_image: "" # should exist in `app/assets/images/`
twitter_account: "@goatsguide"   # required for Twitter Cards
